name: Publish NET.Sdk.BlazorWebAssembly
on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      actions: read
      contents: write
      packages: write
    uses: ./.github/workflows/publish-sdk.yml
    with:
      sdk-name: NET.Sdk.BlazorWebAssembly
      artifact-name: net-sdk-blazor-webassembly
      version-file: src/NET.Sdk.BlazorWebAssembly/VERSION
    secrets: inherit
