name: Publish NET.Sdk
on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      actions: read
      contents: write
      packages: write
    uses: ./.github/workflows/publish-sdk.yml
    with:
      sdk-name: NET.Sdk
      artifact-name: net-sdk
      version-file: src/NET.Sdk/VERSION
    secrets: inherit
